### ISSUE TITLE
404 status code

### ISSUE THREAD

**Issue by AndrejGajdos** [nodeca/probe-image-size#18]
For url: _https://code-maven.com/stack-trace-in-javascript/img/code_maven_128.png_ 

I got 404 error:

```Error
      at DuplexWrapper.<anonymous> (.../node_modules/probe-image-size/http.js:50:16)
      at emitThree (events.js:140:20)
      at DuplexWrapper.emit (events.js:216:7)
      at EventEmitter.ee.on.res (.../node_modules/probe-image-size/node_modules/got/index.js:250:10)
      at emitOne (events.js:115:13)
      at EventEmitter.emit (events.js:210:7)
      at Immediate.setImmediate (.../node_modules/probe-image-size/node_modules/got/index.js:99:8)
      at runCallback (timers.js:781:20)
      at tryOnImmediate (timers.js:743:5)
      at processImmediate [as _immediateCallback] (timers.js:714:5)```

**Comment by puzrin** [comment]
That link returns "no such article" in browser. So, works as expected.

**Comment by AndrejGajdos** [comment]
Thanks for fast response. You are right, I didn't notice that.
