### ISSUE TITLE
ECONTENT unrecognized file format

### ISSUE THREAD

**Issue by CanRau** [nodeca/probe-image-size#20]
```
node node_modules/probe-image-size/support/dump.js 
![gefuellte-paprika-1](https://user-images.githubusercontent.com/5196971/36979931-ea8bd92c-2056-11e8-9161-63f3e19e2a6f.jpg)
gefuellte-paprika-1.jpg
{ ProbeError: unrecognized file format
    at ParserStream.parserEnd (/Users/Can/Sites/react/gaiama-gatsby-content/happygaia-export/node_modules/probe-image-size/stream.js:29:24)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at ParserStream.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'ProbeError',
  message: 'unrecognized file format',
  code: 'ECONTENT' }
```
maybe it's because of this?
> Note. Formats like JPEG & TIFF can store size anywhere (far from the head).

I'm using gatsbyjs where gatsby-plugin-sharp includes your module and only this one image errored, I could fix it for now by resaving it
just opening the issue to let you know and understand whats going on ;-)

**Comment by puzrin** [comment]
I'm sure the reason is different, that comment was to explain big memory use of sync parsers.

But i was able to reproduce your example, and think this is about a new bug.

**Comment by CanRau** [comment]
uh okay good to know, so hopefully it helps :)

**Comment by rlidwka** [comment]
It's because this module missed a minor jpeg feature*. Fixed, thanks!

*\* Namely, padding bytes. There's double 0xFF at offset 0x4B53 in that file which probe didn't know what to do with.*
