### ISSUE TITLE
"x-exr" type image not work

### ISSUE THREAD

**Issue by dontbesatisfied** [nodeca/probe-image-size#63]
I got an error as below, when put xxx.exr image.

```
ProbeError: unrecognized file format
    at ParserStream.parserEnd (/Users/user/Workspace/app/node_modules/probe-image-size/stream.js:39:28)
    at Object.onceWrapper (events.js:421:28)
    at ParserStream.emit (events.js:315:20)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ECONTENT'
}
```

**Comment by puzrin** [comment]
All supported formats are listed in readme https://github.com/nodeca/probe-image-size#probe-image-size. No plans to add all possible "just for fun"
